### ISSUE TITLE
Remove contractname parameter from the add-implementation command

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-cli#13]
Right now, commands like add-implementation require a contract alias and a contract file name.
Eg.
`add-implementation Basil BasilV0`
or when updating:
`add-implementation Basil BasilV1`

If we assume that when a user updates a contract, the original file is simply updated, the 2nd file name parameter is not necessary.

If a user needs to store a reference to and old version, the old version can be renamed to `Basil_old.sol` or `Basil_v0.sol`.

This could imply that the contracts dictionary of package.zos.json simply becomes an array.

**Comment by spalladino** [comment]
@maraoz I think this came up due to a comment from you. Keeping contract name and alias separate in the package.zos.json allows to add more info later to each contract (such as source code hash, that can be used to prevent unnecessary deployments). WDYT about just making the contract alias optional in the command line, and keeping the package.zos.json as is now?

**Comment by spalladino** [comment]
Fixed in #77
