### ISSUE TITLE
Create a wiki for zos-cli

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-cli#273]
We can work on sth similar to the wiki we have in [OZ](https://github.com/OpenZeppelin/openzeppelin-solidity/wiki). Some things to tackle:
- Contribution guide
- Review guidelines
- Gitflow
- Add a reference to the root readme

**Comment by frangio** [comment]
For the record, in OpenZeppelin we're probably going to put almost everything back in a very comprehensive CONTRIBUTING.md file, instead of the wiki. We're interested in contibutors being able to modify it, and although the wiki can be made open for anyone to edit, we prefer to use the same flow of contributions than for code.

**Comment by facuspagnuolo** [comment]
@frangio maybe there is a way to show the `contributing.md` from the wiki instead of putting that content there... if that possible it would be like allowing the contributors to edit the wiki

**Comment by facuspagnuolo** [comment]
Closing in favour of https://github.com/zeppelinos/zos/issues/75
