### ISSUE TITLE
Review and improve logging

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#73]
Make sure that logging is clear and helpful for all commands. Consider removing the prefix with the class name since it may be confusing to the developer.

Ensure there is (almost) always a log entry right before starting a long async action, so the user knows what's happenning.

**Comment by martriay** [comment]
- [x] Make sure that logging is clear and helpful for all commands.
- [x] Consider removing the prefix with the class name since it may be confusing to the developer.
**_Note: as discussed offline, this can be enabled/disabled through the `--verbose` flag, let's continue in #97_**
- [x] Ensure there is (almost) always a log entry right before starting a long async action

No code changes were needed
